<a href="https://colab.research.google.com/github/Deji01/Deep-Learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'1.13.1+cu116'

## 1.0 Scalar

In [2]:
# Scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [3]:
scalar.ndim

0

In [4]:
# get python item within a tensor (only works with one-element tensor)
scalar.item()

10

## 1.1 Vector

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
#  checking number of dimensions
vector.ndim

1

In [7]:
# checking shape of vector
vector.shape

torch.Size([2])

## 1.2 Matrix

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

## 1.3 Tensor

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

## 2.0 Random 

In [14]:
# creating a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6664, 0.7328, 0.6970, 0.0907],
         [0.8065, 0.8030, 0.7789, 0.3906],
         [0.6083, 0.5206, 0.5771, 0.8814]]), torch.float32)

In [15]:
# creating a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
# random_image_size_tensor shaoe and dimension
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## 2.1 Zeros and Ones

In [16]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.shape, zeros.ndim, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.Size([3, 4]), 2, torch.float32)

In [17]:
# creating a tensor of all ones
ones = torch.ones(size=(3,4 ))
ones, ones.shape, ones.ndim, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.Size([3, 4]), 2, torch.float32)

## 3.0 Creating Range and Tensors Like

In [18]:
zero_to_ten = torch.arange(
    start=0,
    end=11,
    step=1
)
zero_to_ten
                           

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# tensors of zeros similar to the size (11) of tensor zero_to_ten can also be created
eleven_zeros = torch.zeros_like(input=zero_to_ten)
eleven_zeros, len(eleven_zeros)

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 11)

In [20]:
# same can be done for ones
eleven_ones = torch.ones_like(input=zero_to_ten)
eleven_ones, eleven_ones.size()

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), torch.Size([11]))

## 4.0 Tensor Data Types

In [21]:
# The default data type for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad                              

(tensor([3., 6., 9.]),
 torch.Size([3]),
 torch.float32,
 device(type='cpu'),
 False)

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16 # same as torch.half
                               )
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## 5.0 Getting Information from Tensors

In [23]:
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Data Type of tensor: {some_tensor.dtype}") # default torch.float32
print(f"Device tensor is stored on: {some_tensor.device}") # default CPU

tensor([[0.7885, 0.4214, 0.2058, 0.9217],
        [0.8100, 0.1659, 0.0259, 0.5715],
        [0.9043, 0.7876, 0.0372, 0.7767]])
Shape of tensor: torch.Size([3, 4])
Data Type of tensor: torch.float32
Device tensor is stored on: cpu


## 6.0 Manipulating Tensors (Tensor Operations)

In [24]:
# creating a tensor of values and adding 10 to it
tensor = torch.tensor([1, 2, 3, 4])
tensor + 10

tensor([11, 12, 13, 14])

In [25]:
# Multiplying by 10
tensor * 10

tensor([10, 20, 30, 40])

In [26]:
# Subtracting and reassigning
tensor = tensor - 10
tensor

tensor([-9, -8, -7, -6])

In [27]:
# Adding and reassigning
tensor += 10
tensor

tensor([1, 2, 3, 4])

In [28]:
# using in-built torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30, 40])

In [29]:
tensor

tensor([1, 2, 3, 4])

In [30]:
torch.isclose(torch.mul(tensor, 10), torch.multiply(tensor, 10))

tensor([True, True, True, True])

## 6.1 Matrix Multiplication

In [31]:
tensor = torch.tensor([1, 2, 3])

In [32]:
tensor.shape

torch.Size([3])

In [33]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [34]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
# "@" symbol can also be used for matrix multiplication, though it is not recommended
tensor @ tensor

tensor(14)

In [36]:
%%time
# Matrix multiplication by hand
# avoid doing operations with for loops at all cost, the are computationally expensive
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 128 µs, sys: 19 µs, total: 147 µs
Wall time: 154 µs


tensor(14)

In [37]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 25 µs, sys: 4 µs, total: 29 µs
Wall time: 32.2 µs


tensor(14)

## 6.2 Shape Errors (One of the most common errors in deep learning)

Tensors need to be of the right shape before they can be matrix multiplied
 1. Their inner dimensions must be the same.

2. outer dimension give the shape of the resulting tensor.

- `(3, 2)` `@` `(3,2)` will produce and error.
- `(2, 3)` `@` `(3,2)` will work. resulting in  -> `(2, 2)`
- `(3, 2)` `@` `(2,3)` will work. resulting in -> `(3, 3)`


In [39]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4], 
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
print(tensor_A.shape)
print(tensor_B.shape)
torch.matmul(tensor_A, tensor_B) # this will produce an error

torch.Size([3, 2])
torch.Size([3, 2])


RuntimeError: ignored

In [40]:
# transpose tensor_B
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [41]:
torch.matmul(tensor_A, tensor_B.T) # this will work

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [42]:
torch.matmul(tensor_A.T, tensor_B) # this will work

tensor([[ 76., 103.],
        [100., 136.]])

In [43]:
# mm is an alias for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [44]:
# y = x * A.T + b
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(
    in_features=2,
    out_features=6
)

linear.state_dict()

OrderedDict([('weight', tensor([[ 0.5406,  0.5869],
                      [-0.1657,  0.6496],
                      [-0.1549,  0.1427],
                      [-0.3443,  0.4153],
                      [ 0.6233, -0.5188],
                      [ 0.6146,  0.1323]])),
             ('bias',
              tensor([ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045]))])

In [45]:
x = tensor_A
x, x.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]), torch.Size([3, 2]))

In [46]:


output = linear(x)
output, output.shape

(tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
        grad_fn=<AddmmBackward0>), torch.Size([3, 6]))

## 6.3 Aggregation (min, max, mean, sum)

In [47]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # will not work without float data type
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [49]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

## 6.4 Positional Min and Max (`torch.argmin()` and `torch.argmax()`)

In [50]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

print(f"Index where min values occurs: {tensor.argmin()}")
print(f"Index where max values occurs: {tensor.argmax()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where min values occurs: 0
Index where max values occurs: 8


## 7.0 Change Tensor Data Type

In [51]:
tensor = torch.arange(10., 100., 10.)
tensor, tensor.dtype

(tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]), torch.float32)

In [52]:
# creating a float16 tensor
float_16_tensor = tensor.type(torch.float16)
float_16_tensor

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [53]:
# creating a int8 tensor
int_8_tensor = tensor.type(torch.int8)
int_8_tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## 8.0 Reshaping, Stacking, Squeezing and Unsqeezing

In [54]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [55]:
# Add an extra dimension

x_reshaped = torch.reshape(x, shape=(1, 7))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [56]:
#  change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [57]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [58]:
# tack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [59]:
# tack tensors beside each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [60]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [61]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7.])

In [62]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [63]:
x_original = torch.rand(size=(224, 224, 3))
x_original.shape

torch.Size([224, 224, 3])

In [64]:
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

## 9.0 Indexing (Selecting data from tensors)

In [65]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [66]:
x = x.reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [67]:
# let's index bracket by bracket

print(f"First square bracket: \n{x[0]}")
print(f"Second square bracket: \n{x[0][0]}")
print(f"Third square bracket: \n{x[0][0][0]}")

First square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: 
tensor([1, 2, 3])
Third square bracket: 
1


In [68]:
#  get all values of the 0th dimension and the oth index of the 1st dimesion
x[:, 0]

tensor([[1, 2, 3]])

In [69]:
# get all values of the 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [70]:
# get all values of the 0th dimension but only 1 of the 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [71]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## 10.0 PyTorch Tensors and Numpy

In [72]:
import torch
import numpy as np

In [73]:
array = np.arange(1.0, 8.0)
array, array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

In [74]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [75]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## 11.0 Reproducibility

In [76]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")

random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [77]:
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(42)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")

random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## 12.0 Running Tensors on GPUs

In [78]:
!nvidia-smi

Wed Feb 22 02:22:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    28W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [79]:
# check for GPU
torch.cuda.is_available()

True

In [80]:
# set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [81]:
torch.cuda.device_count()

1

## 12.1 Putting Tensors (and Models) on the GPU

In [82]:
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [83]:
!nvidia-smi

Wed Feb 22 02:29:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P0    28W /  70W |    570MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## 12.2 Moving Tensors back to CPU

In [84]:
# if the tensor is on GPU, the transformation below will produce and error
tensor_on_gpu.numpy()

TypeError: ignored

In [85]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [86]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')