<a href="https://colab.research.google.com/github/Deji01/Deep-Learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.rand( size=(7,7));
random_tensor

tensor([[0.1740, 0.6307, 0.7340, 0.4962, 0.4201, 0.4715, 0.2379],
        [0.3288, 0.7461, 0.3821, 0.4729, 0.9340, 0.3662, 0.7751],
        [0.7605, 0.6259, 0.7531, 0.1825, 0.9915, 0.9143, 0.6586],
        [0.7066, 0.4894, 0.8420, 0.2455, 0.3264, 0.4780, 0.9098],
        [0.5724, 0.5836, 0.4194, 0.5515, 0.1303, 0.2956, 0.7877],
        [0.3245, 0.6090, 0.8353, 0.6598, 0.7209, 0.9314, 0.9264],
        [0.9489, 0.3283, 0.8151, 0.5362, 0.3971, 0.1333, 0.5403]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_A = torch.rand(size=(1, 7))
tensor_B = torch.rand(size=(1, 7))

# a @ b.T = (1, 7) @ (7, 1) -> (1, 1)

# Perform matrix multiplication 
matmul = torch.mm(tensor_A, tensor_B.T)
matmul

tensor([[2.3166]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
RANDOM_SEED = 0

In [5]:
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(size=(7,7))
tensor, tensor.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 torch.Size([7, 7]))

In [6]:
# Set manual seed
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
new_random_tensor_A = torch.rand(size=(1, 7))
new_random_tensor_B = torch.rand(size=(1, 7))

print(f"Tensor A : {new_random_tensor_A} | Shape : {new_random_tensor_A.shape}")
print(f"Tensor B : {new_random_tensor_B} | Shape : {new_random_tensor_B.shape}")
print(f"Tensor B Transpose: {new_random_tensor_B.T} | Shape : {new_random_tensor_B.T.shape}")
print(f"\nMultiplying Tensor A and B transpose ...\n")

# Matrix multiply tensors
matmul_result = torch.matmul(new_random_tensor_A, new_random_tensor_B.T)
matmul_result, matmul_result.shape

Tensor A : tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]) | Shape : torch.Size([1, 7])
Tensor B : tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689]]) | Shape : torch.Size([1, 7])
Tensor B Transpose: tensor([[0.8964],
        [0.4556],
        [0.6323],
        [0.3489],
        [0.4017],
        [0.0223],
        [0.1689]]) | Shape : torch.Size([7, 1])

Multiplying Tensor A and B transpose ...



(tensor([[1.1173]]), torch.Size([1, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
random_gpu_tensor_A = torch.rand(
    size=(2, 3), 
    device=device)
random_gpu_tensor_B = torch.rand(
    size=(2, 3),
    device=device
)

print(f"\n{random_gpu_tensor_A}")
print(f"\n{random_gpu_tensor_B}")

Device: cuda

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
output_7 = torch.matmul(random_gpu_tensor_A, random_gpu_tensor_B.T)
output_7

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
max = output_7.max()
# Find min
min = torch.min(output_7)

min, max

(tensor(0.2786, device='cuda:0'), tensor(0.7668, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [26]:
# Find arg max
max_idx = torch.argmax(output_7)

# Find arg min
min_idx = output_7.argmin()

min_idx.item(), max_idx.item()

(0, 1)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
TENSOR = torch.rand(size=(1, 1, 1, 10 ))

# Remove single dimensions
squeezed_tensor = torch.squeeze(TENSOR)

# Print out tensors and their shapes
print(TENSOR, TENSOR.shape)
print()
print(squeezed_tensor, squeezed_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
